// <auto-generated />
#nullable enable
namespace AroniumFactures
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings
    {
        
        private static global::System.Resources.ResourceManager? resourceMan;
        
        private static global::System.Globalization.CultureInfo? resourceCulture;
        
        public Strings()
        {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AroniumFactures.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo? Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        public static string AmountLabel => ResourceManager.GetString("AmountLabel", resourceCulture)!;
        
        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture)!;
        
        public static string CreateInvoiceButton => ResourceManager.GetString("CreateInvoiceButton", resourceCulture)!;
        
        public static string CustomerLabel => ResourceManager.GetString("CustomerLabel", resourceCulture)!;
        
        public static string DateLabel => ResourceManager.GetString("DateLabel", resourceCulture)!;
        
        public static string DescriptionLabel => ResourceManager.GetString("DescriptionLabel", resourceCulture)!;
        
        public static string FormTitle => ResourceManager.GetString("FormTitle", resourceCulture)!;
        
        public static string IntroText => ResourceManager.GetString("IntroText", resourceCulture)!;
        
        public static string SliderLabel => ResourceManager.GetString("SliderLabel", resourceCulture)!;
        
        public static string SliderValuePrefix => ResourceManager.GetString("SliderValuePrefix", resourceCulture)!;
        
        public static string SubmitButton => ResourceManager.GetString("SubmitButton", resourceCulture)!;
        
        public static string InvoiceNumber => ResourceManager.GetString("InvoiceNumber", resourceCulture)!;
        
        public static string InvoiceDate => ResourceManager.GetString("InvoiceDate", resourceCulture)!;
        
        public static string PaymentType => ResourceManager.GetString("PaymentType", resourceCulture)!;
        
        public static string ClientLabel => ResourceManager.GetString("ClientLabel", resourceCulture)!;
        
        public static string ICELabel => ResourceManager.GetString("ICELabel", resourceCulture)!;
        
        public static string RefColumn => ResourceManager.GetString("RefColumn", resourceCulture)!;
        
        public static string DesignationColumn => ResourceManager.GetString("DesignationColumn", resourceCulture)!;
        
        public static string QtyColumn => ResourceManager.GetString("QtyColumn", resourceCulture)!;
        
        public static string PriceColumn => ResourceManager.GetString("PriceColumn", resourceCulture)!;
        
        public static string TVAColumn => ResourceManager.GetString("TVAColumn", resourceCulture)!;
        
        public static string TotalColumn => ResourceManager.GetString("TotalColumn", resourceCulture)!;
        
        public static string TotalHT => ResourceManager.GetString("TotalHT", resourceCulture)!;
        
        public static string Taxe => ResourceManager.GetString("Taxe", resourceCulture)!;
        
        public static string TotalTTC => ResourceManager.GetString("TotalTTC", resourceCulture)!;
        
        public static string AddItemButton => ResourceManager.GetString("AddItemButton", resourceCulture)!;
        
        public static string RemoveItemButton => ResourceManager.GetString("RemoveItemButton", resourceCulture)!;
        
        public static string CompanyName => ResourceManager.GetString("CompanyName", resourceCulture)!;
        
        public static string CompanyAddress => ResourceManager.GetString("CompanyAddress", resourceCulture)!;
        
        public static string InvoiceTitle => ResourceManager.GetString("InvoiceTitle", resourceCulture)!;
        
        public static string GenerateButton => ResourceManager.GetString("GenerateButton", resourceCulture)!;
        
        public static string ChooseLogo => ResourceManager.GetString("ChooseLogo", resourceCulture)!;
        
        public static string AmountInWords => ResourceManager.GetString("AmountInWords", resourceCulture)!;
    }
}

